version: '3.7'

services:
  webapp:
    build: .
    image: docker-hub-update-notifier
    container_name: webapp
    restart: always
    environment:
      TZ: Asia/Tokyo

  batch:
    image: docker-hub-update-notifier
    container_name: batch
    restart: always
    command: python scheduler.py batch
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      TZ: "Asia/Tokyo"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local