version: '3.7'

services:
  docker-hub-update-notifier:
    build: .
    image: docker-hub-update-notifier
    container_name: notifier
    restart: always
    volumes:
      - ./data:/data
