version: '3.7'

services:
  webapp:
    build: .
    image: docker-hub-update-notifier
    container_name: webapp
    restart: always
    environment:
      TZ: Asia/Tokyo
      ALLOWED_HOSTS: 'localhost, 127.0.0.1'
      DB_ENGINE: postgresql
      DB_HOST: django_postgres
      DB_NAME: django
      DB_USER: django
      DB_PASS: django
      EMAIL_BACKEND: smtp
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_LOCALTIME: 'false'
      DEFAULT_FROM_EMAIL: ''
      STATIC_ROOT: '/static'
    volumes:
      - django_statics:/static:rw
    depends_on:
      - postgres

  batch:
    image: docker-hub-update-notifier
    container_name: batch
    restart: always
    command: /bin/sh -c ". ~/.profile && python scheduler.py batch"
    environment:
      TZ: Asia/Tokyo
      DB_ENGINE: postgresql
      DB_HOST: django_postgres
      DB_NAME: django
      DB_USER: django
      DB_PASS: django
      EMAIL_BACKEND: smtp
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_LOCALTIME: 'false'
      DEFAULT_FROM_EMAIL: ''
    depends_on:
      - postgres

  postgres:
    image: postgres:12.1-alpine
    container_name: django_postgres
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      TZ: Asia/Tokyo
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:1.17.8-alpine
    container_name: django_nginx
    ports:
      - 80:80
    restart: always
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - django_statics:/usr/share/nginx/html/static:ro
    depends_on:
      - webapp

volumes:
  pgdata:
    driver: local
  django_statics:
    driver: local