version: '3.7'

services:
  webapp:
    build: .
    image: docker-hub-update-notifier
    container_name: webapp
    restart: always
    environment:
      LANGUAGE_CODE: ja
      TZ: Asia/Tokyo
      ALLOWED_HOSTS: ''
      DB_ENGINE: postgresql
      DB_HOST: postgres
      DB_NAME: django
      DB_USER: django
      DB_PASS: django
      EMAIL_BACKEND: smtp
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_LOCALTIME: 'false'
      DEFAULT_FROM_EMAIL: ''
    depends_on:
      - postgres

  batch:
    image: docker-hub-update-notifier
    container_name: batch
    restart: always
    command: bash -c ". ~/bashrc && python scheduler.py batch"
    environment:
      LANGUAGE_CODE: ja
      TZ: Asia/Tokyo
      DB_ENGINE: postgresql
      DB_HOST: postgres
      DB_NAME: django
      DB_USER: django
      DB_PASS: django
      EMAIL_BACKEND: smtp
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USE_TLS: 'true'
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_LOCALTIME: 'false'
      DEFAULT_FROM_EMAIL: ''
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: django
      TZ: "Asia/Tokyo"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp

volumes:
  pgdata:
    driver: local
