[tool.poetry]
name = "DockerHubUpdateNotifier"
version = "1.1.9"
description = ""
authors = ["roy-n-roy"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.0.6"
django-bootstrap4 = "^1.1.1"
requests = "^2.23.0"
schedule = "^0.6.0"
CacheControl = {extras = ["filecache"], version = "^0.12.6"}
uWSGI = {version = "^2.0.18", optional = true}
psycopg2 = {version = "^2.8.5", optional = true}
psycopg2-binary = {version = "^2.8.5", optional = true}
sentry-sdk = {version = "^0.14.3", optional = true}

[tool.poetry.dev-dependencies]
autopep8 = "^1.5.2"
flake8 = "^3.8.1"
rope = "^0.17.0"

[tool.poetry.extras]
pgsql = ["psycopg2", "psycopg2-binary"]
sentry = ["sentry-sdk"]
uwsgi = ["uWSGI"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
