# Generated by Django 3.0.2 on 2020-01-19 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockerhub_user', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=1024)),
                ('tag', models.CharField(max_length=1024)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('dockerhub_user', 'name', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Watching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='repos.Repository')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'repository')},
            },
        ),
    ]
