# Generated by Django 3.0.6 on 2020-05-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryTagHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField()),
                ('repository_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.RepositoryTag')),
            ],
            options={
                'unique_together': {('repository_tag', 'updated')},
            },
        ),
        migrations.CreateModel(
            name='WatichingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.RepositoryTagHistory')),
                ('watching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repos.Watching')),
            ],
        ),
    ]
