# Generated by Django 3.0.2 on 2020-01-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notify_to_email',
            field=models.BooleanField(default=True, help_text='If enabled, it will notify your email address of updates to the Docker repository.', verbose_name='is notity to E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='If set in this field, the Webhook URL you enter will be notified of updates to the Docker repository.', max_length=500, null=True, verbose_name='Webhook URL'),
        ),
    ]
