# Generated by Django 3.0.2 on 2020-01-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200123_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='en', help_text='Language used to display.', max_length=3, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='If set in this field, the Webhook URL you enter will be notified of updates to the Docker repository .Supported for Incoming Webhook URL of Slack and IFTTT.', max_length=500, null=True, verbose_name='Webhook URL'),
        ),
    ]
