name: Generate requirements.txt

on:
  push:
    tags: 
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Git config
      run: |
        git config --global user.name "github-actions"
        git config --global user.email actions@github.com

    - name: Install Pipenv
      run: |
        python -m pip install -U pip
        pip install pipenv

    - name: Get Version
      run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\/v/}

    - name: Genetate and commit requirements.txt
      run: |
        git checkout -B release
        pipenv lock --requirements > ${{ github.workspace }}/requirements.txt
        cd ${{ github.workspace }}/production
        pipenv lock --requirements >> ${{ github.workspace }}/requirements.txt
        cd ${{ github.workspace }}
        git add requirements.txt
        git commit -m "release ${VERSION}"
        git ls-remote --exit-code origin release-${VERSION} && git push origin :release-${VERSION}
        git tag release-${VERSION}
        git push origin release
        git push origin release-${VERSION}

    - name: Notify Slack
      if: always()
      uses: pioug/le-slack-message@v1.0.0
      with:
        ACTION_NAME: Build Docker Image@roy-n-roy/DockerHubUpdateNotifier
        JOB: ${{ toJson(job) }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
